app/models.py
from datetime import datetime
from flask import current_app
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login

reviews = db.Table(
    'reviews',
    db.Column('id', db.Integer, primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('book_id', db.Integer, db.ForeignKey('book.id')),
    db.Column('rating', db.Integer),
    db.Column('comment', db.String(300)),
    db.Column('time_review', db.DateTime, default=datetime.utcnow)
)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    isbn = db.Column(db.String)
    title = db.Column(db.String)
    author = db.Column(db.String)
    year = db.Column(db.Integer)

    def __repr__(self):
        return '<Book {}>'.format(self.isbn)

app/__init__.py
import logging
from flask import Flask, request
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import Config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.error import bp as error_bp
    app.register_blueprint(error_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app, jsonify
from flask_login import current_user, login_required
from app.models import User, Book
from app.main import bp
from app import db
from datetime import datetime
from sqlalchemy import text
import os
import requests
import json


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():

    # Postgresql
    sql = text('SELECT title, author, year, isbn FROM book ORDER BY RAND() LIMIT 4')

    # SQL Server
    # sql = text(
    #     'SELECT TOP 4 title, author, "year", isbn FROM book ORDER BY NEWID()')
    q = db.engine.execute(sql)
    return render_template('index.html', title='Home', rnd_book=q)


@bp.route('/search', methods=['GET'])
@login_required
def search():
    search_book = request.args.get('book')

    if not search_book:
        flash('You must provide a book.', 'warning')
        return render_template('index.html', title='Error')
    elif len(search_book) < 3:
        flash('You should enter more than 3 characters', 'warning')
        return render_template('index.html', title='Error')
    else:
        query = '%' + search_book + '%'
        sql = text('SELECT title, author, year, isbn FROM book WHERE \
                    isbn LIKE :query OR \
                    title LIKE :query OR \
                    author LIKE :query LIMIT 4')
        book_result = db.engine.execute(sql, {"query": query})

        if book_result.rowcount == 0:
            flash("we can't find books with that description.", "warning")
        return render_template('index.html', rnd_book=book_result)


def get_rating(isbn, book_result):
    key = '8LMzrOv53AsM8C5D8hag'
    query = requests.get("https://www.goodreads.com/book/review_counts.json",
                         params={"key": key, "isbn": isbn})
    response = query.json()
    response = response['books'][0]
    book_result.append(response)
    return book_result


@bp.route('/book/<isbn>', methods=['GET', 'POST'])
@login_required
def book(isbn):
    sql = text('SELECT title, author, year, isbn FROM book WHERE isbn LIKE :isbn')
    book_result = db.engine.execute(sql, {'isbn': isbn})
    book_result = book_result.fetchall()

    if book_result is None:
        return render_template('/error/404.html')

    sql = text('SELECT id FROM book WHERE isbn = :isbn')
    row = db.engine.execute(sql, {'isbn': isbn})

    if request.method == 'POST':
        currentUser = current_user.get_id()
        rating = request.form.get('rating')
        comment = request.form.get('comment')

        bookId = row.fetchone()
        bookId = bookId[0]

        sql = text(
            'SELECT * FROM reviews WHERE user_id = :user_id AND book_id = :book_id ')
        row2 = db.engine.execute(sql, {'user_id': currentUser,
                                       'book_id': bookId})

        if row2.rowcount == 1:
            flash('You already submitted a review for this book', 'warning')
            return redirect("/book/" + isbn)

        rating = int(rating)

        sql = text('INSERT INTO reviews (user_id, book_id, comment, rating) VALUES \
                    (:user_id, :book_id, :comment, :rating)')

        db.engine.execute(sql, {'user_id': currentUser,
                                'book_id': bookId,
                                'comment': comment,
                                'rating': rating})
        db.session.commit()
        flash('review submitted', 'info')

        return redirect('/book/'+isbn)

    else:
        book = row.fetchone()
        book = book[0]

        sql = text('SELECT "user".username, reviews."comment", reviews.rating \
                            FROM "user" \
                            INNER JOIN reviews \
                            ON "user".id = reviews.user_id \
                            WHERE book_id = :book')

        results = db.engine.execute(sql, {'book': book})
        reviews = results.fetchall()

    return render_template('book.html', book_result=book_result, reviews=reviews)


@bp.route('/api/<isbn>', methods=['GET'])
@login_required
def api_call(isbn):

    sql = text("SELECT title, author, year, isbn, \
                COUNT(reviews.id) as review_count, \
                AVG(reviews.rating) as average_score \
                FROM book \
                INNER JOIN reviews \
                ON book.id = reviews.book_id \
                WHERE isbn = :isbn \
                GROUP BY title, author, year, isbn;")

    row = db.engine.execute(sql, {'isbn': isbn})

    if row.rowcount != 1:
        return jsonify({"Error": "Invalid book ISBN"}), 422

    tmp = row.fetchone()

    print(tmp)
    print('-------------------------------')

    result = dict(tmp.items())

    result['average_score'] = float('%.2f' % (result['average_score']))

    print(result)

    return jsonify(result)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"> -->

    <title>{% block title %}{{ title }}{% endblock title %}</title>
</head>

<style>
  link-a-a a {
    color: #dc3545;
  }
  link-a-a a:hover {
    color: white;
    text-decoration: none;
  }

</style>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light border">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index')}}">BookStore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="navbar-collapse collapse" id="navbarNavDropdown">
          {% if current_user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="{{ url_for('auth.logout') }}" class="nav-link text-danger">Log Out</a></li>
            </ul>
          {% else%}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="{{ url_for('auth.register') }}" class="nav-link">Register</a></li>
                <li class="nav-item"><a href="{{ url_for('auth.login') }}" class="nav-link">Login</a></li>
            </ul>
          {% endif %}
        </div>
      </div>
      </nav>

      {% block content %}
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                    <span>{{ message }}</span> 
                  </div>
                {% endfor %}
            {% endif %}
            {% endwith %}

            {% block app_content %} {% endblock app_content %}
        </div>
      {% endblock content %}  



</body>
</html>

app/templates/book.html
{% extends 'base.html' %}

<style>
#art a img {
    display: block;
    margin: auto;
}

</style>

{% block app_content %}

<br>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <img src="http://covers.openlibrary.org/b/isbn/{{ book_result[0]['isbn'] }}-M.jpg" alt="{{ book_result[0]['isbn'] }}" width="150px" 
                style="margin: auto; display: block;">
            </div>
            <div class="col-sm-4">
                <h3>{{ book_result[0]['title'] }}</h3>
                <h5>By: {{ book_result[0]['author'] }}<h5>
                <h5>Published: {{ book_result[0]['year']}}</h5>
                <h5>ISBN: {{ book_result[0]['isbn']}}</h5>
            </div>   
                     
        </div>
    </div>
    <hr>
    <form method="POST" class="form-border">
        <div class="form-row">
            <label for="rating" style="padding: 6px;">Rate this book:</label>
            <div class="form-group col-sm-1">
                <select id="rating" name="rating" class="form-control" required>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option selected value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <div class="form-group col-sm-8">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Say something</span>
                    </div>
                    <textarea name="comment" id="comment" class="form-control" rows="1" required></textarea>
                </div>
            </div>
            <div class="form-group col-sm">
                <button class="btn btn-success" type="submit">Submit</button>
            </div>
        </div>
    </form>

    <hr>
    <h4>User review:</h4>
    <div class="container">
        {% for review in reviews %}
        <div class="list-group list-group-horizontal">
            <li class="list-group-item">{{ review['username'] }} ratting {{ review['rating'] }} said: </li>
            <li class="list-group-item">{{ review['comment'] }}</li>

        </div>           
        {% endfor %}
    </div>

{% endblock app_content %}

app/templates/index.html
{% extends 'base.html' %}


{% block app_content %}

    <h1 style="text-align: center;">Hi, {{ current_user.username }}!</h1>
    <br>

    <h2 style="text-align: center;">Search for book:</h2>
    <form action="{{ url_for('main.search') }}" method="GET" class="form-group">
        <div class="input-group mb-3">
            <input name="book" type="text" class="form-control" placeholder="ISBN, Author or Title" aria-label="ISBN, Author or Title" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-outline-primary" type="submit">Search</button>
            </div>
          </div>
        <small id="bookHelp" class="form-text text-muted">Example: 0375508325, Cosmos or Carl Sagan</small>
    </form>

    <h4>Have You Read:</h4>
   
    <div class="container-fluid mt-4">
        <div class="row justify-content-center">
            <div class="card-deck col-auto mb-4">
                {% for book in rnd_book %}
                <div class="card border-primary mb-3">
                    <div class="card-header" style="text-align: left;"><h5>{{ book[0] }}</h4></div>
                        <div class="card-body">
                            <h6 class="card-text">Author: {{book[1]}}</h6>
                            <h6 class="card-text">Year: {{book[2]}}</h6>
                            <h6 class="card-text">Isbn: {{book[3]}}</h6>
                            <hr>
                            <img src="http://covers.openlibrary.org/b/isbn/{{ book[3] }}-M.jpg" alt="{{ book[0] }}" class="card-img" width="110px">
                        </div>
                        <div class="card-footer">
                            <a href="{{ url_for('main.book', isbn=book[3]) }}">Go to book page</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>



    </div>    

          
{% endblock app_content %}